module.exports = [
  {
    branch: 'EC',
    semester: 3,
    title: 'Line Follower Robot',
    type: 'MINI',
    description:
      'An autonomous robot that follows a black line on a white surface using IR sensor arrays and a microcontroller, demonstrating closed-loop control.',
    objectives: [
      'Build an IR sensor array to detect the line',
      'Implement a PID or logic-based steering algorithm',
      'Calibrate motor speed for smooth turns',
    ],
    technologies: ['8051/Arduino', 'IR sensors', 'DC motors', 'L293D driver'],
    prerequisites: 'Digital electronics basics, C programming',
    timeline_weeks: 6,
    deliverables: ['Working robot', 'Circuit schematic', 'Project report'],
    difficulty: 'Intermediate',
    github_url: '',
    report_url: '',
  },
  {
    branch: 'EC',
    semester: 3,
    title: 'Scrolling LED Message Display',
    type: 'MINI',
    description:
      'A dot-matrix or 7-segment display that scrolls a text message using multiplexing and shift registers.',
    objectives: [
      'Interface LED matrix with the microcontroller',
      'Implement character fonts and scrolling logic',
      'Control brightness via multiplexing',
    ],
    technologies: ['8051', 'LED matrices', 'Shift registers', 'Timer interrupts'],
    prerequisites: 'Digital electronics, microcontroller basics',
    timeline_weeks: 5,
    deliverables: ['Scrolling display', 'Font library', 'Report'],
    difficulty: 'Beginner',
    github_url: '',
    report_url: '',
  },
  {
    branch: 'EC',
    semester: 3,
    title: 'Water Level Indicator with Alarm',
    type: 'MINI',
    description:
      'A sensor-based system that detects water levels in a tank and sounds an alarm or switches a pump automatically.',
    objectives: [
      'Design a level-sensing probe circuit',
      'Display levels with LEDs',
      'Add automatic pump control',
    ],
    technologies: ['Transistors', 'Op-amps', 'Relays', 'BCD-to-7-segment'],
    prerequisites: 'Analog electronics basics',
    timeline_weeks: 4,
    deliverables: ['Working model', 'Circuit diagram', 'Report'],
    difficulty: 'Beginner',
    github_url: '',
    report_url: '',
  },
  {
    branch: 'EC',
    semester: 4,
    title: 'RFID-based Attendance System',
    type: 'MINI',
    description:
      'An attendance system that reads student RFID cards and logs entries with timestamps.',
    objectives: [
      'Interface an RFID reader',
      'Maintain a student database',
      'Generate daily attendance reports',
    ],
    technologies: ['RFID reader (EM-18)', '8051', 'UART', 'PC application'],
    prerequisites: 'Microprocessors, serial communication',
    timeline_weeks: 6,
    deliverables: ['Working attendance system', 'Database schema', 'Report'],
    difficulty: 'Intermediate',
    github_url: '',
    report_url: '',
  },
  {
    branch: 'EC',
    semester: 4,
    title: 'Electronic Voting Machine',
    type: 'MINI',
    description:
      'A microcontroller-based voting machine with a keypad for voting, instant display and locked tallying.',
    objectives: [
      'Design the voting logic',
      'Use interrupts for candidate selection',
      'Prevent duplicate votes',
    ],
    technologies: ['8051', 'Keypad', 'LCD', 'EEPROM'],
    prerequisites: 'Microprocessors, digital design',
    timeline_weeks: 4,
    deliverables: ['Working EVM', 'Code', 'Report'],
    difficulty: 'Beginner',
    github_url: '',
    report_url: '',
  },
  {
    branch: 'EC',
    semester: 4,
    title: 'Digital Clock using 7-Segment Displays',
    type: 'MINI',
    description:
      'A real-time digital clock with multiplexed 7-segment displays, using timers for accurate timekeeping.',
    objectives: [
      'Implement timekeeping with timer interrupts',
      'Multiplex multiple displays',
      'Add time setting buttons',
    ],
    technologies: ['8051', '7-segment displays', 'Timers', 'Interrupts'],
    prerequisites: 'Microprocessors',
    timeline_weeks: 5,
    deliverables: ['Working clock', 'Schematic', 'Report'],
    difficulty: 'Beginner',
    github_url: '',
    report_url: '',
  },
  {
    branch: 'EC',
    semester: 5,
    title: 'IoT Temperature Monitoring System',
    type: 'MINI',
    description:
      'A system that reads temperature from a sensor and publishes it to a dashboard over Wi-Fi or GSM.',
    objectives: [
      'Interface LM35/DHT11 with the MCU',
      'Transmit data over a network',
      'Build a simple dashboard',
    ],
    technologies: ['ESP8266/NodeMCU', 'DHT11/LM35', 'MQTT/HTTP', 'Web dashboard'],
    prerequisites: 'Embedded systems, networking basics',
    timeline_weeks: 7,
    deliverables: ['Sensor node', 'Dashboard', 'Report'],
    difficulty: 'Intermediate',
    github_url: '',
    report_url: '',
  },
  {
    branch: 'EC',
    semester: 5,
    title: 'GSM-based Home Security Alert',
    type: 'MINI',
    description: 'A security system that sends SMS alerts when motion or intrusion is detected.',
    objectives: [
      'Interface PIR sensor and GSM module',
      'Send SMS alerts on detection',
      'Add arming/disarming controls',
    ],
    technologies: ['8051/Arduino', 'SIM800 GSM', 'PIR sensor', 'AT commands'],
    prerequisites: 'Embedded systems, serial communication',
    timeline_weeks: 6,
    deliverables: ['Working prototype', 'AT command set', 'Report'],
    difficulty: 'Intermediate',
    github_url: '',
    report_url: '',
  },
  {
    branch: 'EC',
    semester: 5,
    title: 'DC Motor Speed Controller with PWM',
    type: 'MINI',
    description:
      'A PWM-based speed controller for a DC motor with display of speed and direction control.',
    objectives: [
      'Generate PWM with the microcontroller',
      'Measure speed with an encoder',
      'Display speed and direction',
    ],
    technologies: ['8051/AVR', 'PWM', 'Optical encoder', 'LCD'],
    prerequisites: 'Embedded programming',
    timeline_weeks: 5,
    deliverables: ['Working controller', 'Schematic', 'Report'],
    difficulty: 'Intermediate',
    github_url: '',
    report_url: '',
  },
  {
    branch: 'EC',
    semester: 6,
    title: 'Smart Home Automation System',
    type: 'MAJOR',
    description:
      'A home automation system controlling lights, fans and appliances through a mobile app or IR remote with feedback.',
    objectives: [
      'Control multiple appliances reliably',
      'Provide remote operation',
      'Include safety features like overload cut-off',
    ],
    technologies: ['ESP32', 'Relays', 'IR/Bluetooth', 'Mobile app'],
    prerequisites: 'Embedded systems, communication protocols',
    timeline_weeks: 10,
    deliverables: ['Complete system', 'Mobile app', 'Full report'],
    difficulty: 'Advanced',
    github_url: '',
    report_url: '',
  },
  {
    branch: 'EC',
    semester: 6,
    title: 'Automatic Plant Irrigation System',
    type: 'MAJOR',
    description:
      'A soil-moisture-based irrigation controller that waters plants automatically and logs usage.',
    objectives: [
      'Sense soil moisture accurately',
      'Control a pump automatically',
      'Log watering events',
    ],
    technologies: ['Microcontroller', 'Soil moisture sensor', 'Relay pump', 'RTC'],
    prerequisites: 'Sensors, embedded C',
    timeline_weeks: 8,
    deliverables: ['Working system', 'Calibration data', 'Report'],
    difficulty: 'Intermediate',
    github_url: '',
    report_url: '',
  },
  {
    branch: 'EC',
    semester: 6,
    title: 'Voice-Controlled Home Appliance',
    type: 'MAJOR',
    description:
      'Control appliances by voice commands using a smartphone assistant and a Bluetooth/Wi-Fi switchboard.',
    objectives: [
      'Process voice commands',
      'Translate commands to relay actions',
      'Provide feedback responses',
    ],
    technologies: ['ESP32', 'Bluetooth/Wi-Fi', 'Relay board', 'Voice assistant app'],
    prerequisites: 'Embedded systems, mobile apps',
    timeline_weeks: 9,
    deliverables: ['Working switchboard', 'App', 'Report'],
    difficulty: 'Advanced',
    github_url: '',
    report_url: '',
  },
  {
    branch: 'ICT',
    semester: 3,
    title: 'Library Management System',
    type: 'MINI',
    description:
      'A C-based console application managing book records, members and issue/return transactions with file storage.',
    objectives: [
      'Store and search book records',
      'Track issue and return dates',
      'Generate member reports',
    ],
    technologies: ['C', 'File handling', 'Linked lists', 'Structures'],
    prerequisites: 'Programming in C',
    timeline_weeks: 5,
    deliverables: ['Console application', 'Sample data', 'Report'],
    difficulty: 'Beginner',
    github_url: '',
    report_url: '',
  },
  {
    branch: 'ICT',
    semester: 3,
    title: 'Student Result Analyzer',
    type: 'MINI',
    description:
      'A program that computes class statistics, grade distributions and toppers from result data.',
    objectives: ['Parse result data files', 'Compute averages and distributions', 'Rank students'],
    technologies: ['C', 'Arrays', 'Sorting', 'File I/O'],
    prerequisites: 'Data structures basics',
    timeline_weeks: 4,
    deliverables: ['Analyzer program', 'Sample data', 'Report'],
    difficulty: 'Beginner',
    github_url: '',
    report_url: '',
  },
  {
    branch: 'ICT',
    semester: 3,
    title: 'Expression Calculator with Stack',
    type: 'MINI',
    description:
      'A scientific expression calculator that converts infix to postfix and evaluates it using stacks.',
    objectives: [
      'Implement infix to postfix conversion',
      'Evaluate with operator precedence',
      'Support functions and brackets',
    ],
    technologies: ['C/C++', 'Stacks', 'Parsing'],
    prerequisites: 'Stacks and queues',
    timeline_weeks: 4,
    deliverables: ['Calculator', 'Test cases', 'Report'],
    difficulty: 'Intermediate',
    github_url: '',
    report_url: '',
  },
  {
    branch: 'ICT',
    semester: 4,
    title: 'Hospital Management System',
    type: 'MINI',
    description: 'A database application managing patients, doctors, appointments and billing.',
    objectives: [
      'Design a normalized hospital schema',
      'Implement patient and appointment workflows',
      'Generate billing reports',
    ],
    technologies: ['SQL', 'DBMS', 'Optional PHP frontend'],
    prerequisites: 'DBMS, SQL',
    timeline_weeks: 6,
    deliverables: ['Database', 'Queries and reports', 'Report'],
    difficulty: 'Intermediate',
    github_url: '',
    report_url: '',
  },
  {
    branch: 'ICT',
    semester: 4,
    title: 'Inventory Management System',
    type: 'MINI',
    description: 'A system to track stock, suppliers and reorder levels with transaction logging.',
    objectives: [
      'Track stock in and stock out',
      'Alert on reorder levels',
      'Generate supplier reports',
    ],
    technologies: ['SQL', 'Views', 'Triggers'],
    prerequisites: 'DBMS',
    timeline_weeks: 5,
    deliverables: ['Database application', 'Triggers', 'Report'],
    difficulty: 'Intermediate',
    github_url: '',
    report_url: '',
  },
  {
    branch: 'ICT',
    semester: 4,
    title: 'Bank Transaction System',
    type: 'MINI',
    description:
      'A simulated banking application with accounts, deposits, withdrawals and transaction history, enforcing ACID properties.',
    objectives: [
      'Implement account management',
      'Enforce transaction atomicity',
      'Show transaction history',
    ],
    technologies: ['SQL', 'Transactions', 'Concurrency control'],
    prerequisites: 'DBMS, transactions',
    timeline_weeks: 5,
    deliverables: ['Working system', 'Concurrency tests', 'Report'],
    difficulty: 'Intermediate',
    github_url: '',
    report_url: '',
  },
  {
    branch: 'ICT',
    semester: 5,
    title: 'College Website',
    type: 'MINI',
    description:
      'A multi-page college website with news, courses, faculty pages and a contact form.',
    objectives: [
      'Build semantic responsive pages',
      'Add dynamic content with JavaScript',
      'Implement the contact form with PHP',
    ],
    technologies: ['HTML', 'CSS', 'JavaScript', 'PHP'],
    prerequisites: 'Web programming',
    timeline_weeks: 6,
    deliverables: ['Live site', 'Source code', 'Report'],
    difficulty: 'Beginner',
    github_url: '',
    report_url: '',
  },
  {
    branch: 'ICT',
    semester: 5,
    title: 'Online Quiz System',
    type: 'MINI',
    description: 'A quiz platform with timed tests, automatic scoring and result storage.',
    objectives: ['Manage question banks', 'Run timed quizzes', 'Store and display results'],
    technologies: ['PHP', 'MySQL', 'JavaScript', 'AJAX'],
    prerequisites: 'Web programming, DBMS',
    timeline_weeks: 6,
    deliverables: ['Working quiz app', 'Question bank', 'Report'],
    difficulty: 'Intermediate',
    github_url: '',
    report_url: '',
  },
  {
    branch: 'ICT',
    semester: 5,
    title: 'Chat Application',
    type: 'MINI',
    description:
      'A real-time chat application with rooms, user list and message history using AJAX polling or WebSockets.',
    objectives: [
      'Implement user authentication',
      'Send and receive messages in real time',
      'Store chat history',
    ],
    technologies: ['PHP/Node.js', 'MySQL', 'AJAX/WebSockets'],
    prerequisites: 'Web programming, networking',
    timeline_weeks: 7,
    deliverables: ['Working chat app', 'Database', 'Report'],
    difficulty: 'Intermediate',
    github_url: '',
    report_url: '',
  },
  {
    branch: 'ICT',
    semester: 6,
    title: 'E-commerce Product Store',
    type: 'MAJOR',
    description:
      'A small e-commerce platform with product catalog, cart, orders and a simple payment flow.',
    objectives: [
      'Build product catalog and search',
      'Implement cart and checkout',
      'Manage orders and stock',
    ],
    technologies: ['Python/Django or Node.js', 'SQL', 'JavaScript', 'REST API'],
    prerequisites: 'Web development, databases',
    timeline_weeks: 10,
    deliverables: ['Working store', 'Admin panel', 'Full report'],
    difficulty: 'Advanced',
    github_url: '',
    report_url: '',
  },
  {
    branch: 'ICT',
    semester: 6,
    title: 'Weather Dashboard with API',
    type: 'MINI',
    description:
      'A weather dashboard that fetches live data from a public API and visualizes forecasts.',
    objectives: ['Consume a weather API', 'Visualize data with charts', 'Add location search'],
    technologies: ['Python', 'Requests', 'Matplotlib', 'Flask/Django'],
    prerequisites: 'Python, HTTP/JSON',
    timeline_weeks: 6,
    deliverables: ['Dashboard', 'API integration', 'Report'],
    difficulty: 'Intermediate',
    github_url: '',
    report_url: '',
  },
  {
    branch: 'ICT',
    semester: 6,
    title: 'Student Placement Portal',
    type: 'MAJOR',
    description:
      'A portal where companies post jobs, students apply, and coordinators track placements.',
    objectives: [
      'Manage company and student profiles',
      'Implement job applications and shortlisting',
      'Generate placement statistics',
    ],
    technologies: ['Python/Django', 'SQL', 'JavaScript', 'Bootstrap'],
    prerequisites: 'Full stack development',
    timeline_weeks: 10,
    deliverables: ['Portal', 'Statistics dashboard', 'Report'],
    difficulty: 'Advanced',
    github_url: '',
    report_url: '',
  },
  {
    branch: 'ICT',
    semester: 6,
    title: 'College Chatbot Assistant',
    type: 'MINI',
    description:
      'A rule-based chatbot answering FAQs about admissions, fees, timetables and events.',
    objectives: [
      'Build an FAQ knowledge base',
      'Implement intent matching',
      'Integrate with a web chat widget',
    ],
    technologies: ['Python', 'Flask', 'NLP basics', 'JavaScript widget'],
    prerequisites: 'Python, web basics',
    timeline_weeks: 7,
    deliverables: ['Chatbot', 'Web widget', 'Report'],
    difficulty: 'Intermediate',
    github_url: '',
    report_url: '',
  },
];
